// Generate the v3 OKLCH tonal ramps.
//
// Phase 3 §01: "OKLCH 100-900 tonal ramps per role, replacing alpha-tint
// literals ... Tints, hovers and borders come from ramp steps -- 700-900 for
// fills on dark ground, 100-300 for text on tints -- replacing every
// rgba(21,93,255,0.12)-style literal. Swatches are illustrative; generate
// finals in OKLCH."
//
// So: this is that generation, run once and committed, not a build step. Each
// role keeps its seed hue and its chroma character; every role shares ONE
// perceptual lightness scale, which is the whole point of doing it in OKLCH —
// step 500 of blue and step 500 of success read as the same weight, so a
// success chip and an info chip sit at the same visual level instead of one
// shouting.
//
// Chroma is clamped per step to what sRGB can actually hold at that lightness,
// because an out-of-gamut OKLCH colour silently clips to something else and
// the "shared lightness" promise quietly breaks.
//
// Run: pnpm --filter @workspace/scripts run build:mx-ramps

const SEEDS: Record<string, string> = {
  blue:    "#155dff",  // primary — v2.0 identity, kept
  cyan:    "#16d9ff",  // intelligence accent
  neutral: "#8796ac",
  success: "#35d96f",
  danger:  "#ff4f61",
  warning: "#f7c948",
};

/** One shared perceptual lightness scale. 100 = lightest, 900 = darkest. */
const STEPS: Record<number, number> = {
  100: 0.94, 200: 0.87, 300: 0.78, 400: 0.69, 500: 0.60,
  600: 0.51, 700: 0.42, 800: 0.33, 900: 0.24,
};

// ── colour maths ──────────────────────────────────────────────────────
const srgbToLin = (v: number) => (v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4);
const linToSrgb = (v: number) => (v <= 0.0031308 ? 12.92 * v : 1.055 * v ** (1 / 2.4) - 0.055);

function hexToOklch(hex: string): { L: number; C: number; h: number } {
  const n = hex.replace("#", "");
  const [r, g, b] = [0, 2, 4].map((i) => srgbToLin(parseInt(n.slice(i, i + 2), 16) / 255));
  const l = Math.cbrt(0.4122214708 * r! + 0.5363325363 * g! + 0.0514459929 * b!);
  const m = Math.cbrt(0.2119034982 * r! + 0.6806995451 * g! + 0.1073969566 * b!);
  const s = Math.cbrt(0.0883024619 * r! + 0.2817188376 * g! + 0.6299787005 * b!);
  const L = 0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s;
  const A = 1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s;
  const B = 0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s;
  return { L, C: Math.hypot(A, B), h: ((Math.atan2(B, A) * 180) / Math.PI + 360) % 360 };
}

function oklchToHex(L: number, C: number, hDeg: number): string | null {
  const h = (hDeg * Math.PI) / 180;
  const a = C * Math.cos(h), b = C * Math.sin(h);
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.2914855480 * b;
  const [l, m, s] = [l_ ** 3, m_ ** 3, s_ ** 3];
  const lin = [
    +4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s,
  ];
  if (lin.some((v) => v < -0.0008 || v > 1.0008)) return null;
  return "#" + lin
    .map((v) => Math.round(Math.min(1, Math.max(0, linToSrgb(v))) * 255).toString(16).padStart(2, "0"))
    .join("");
}

/** Largest in-gamut chroma at this lightness and hue, at or below `want`. */
function fitChroma(L: number, want: number, h: number): { hex: string; C: number } {
  let lo = 0, hi = want;
  let best = oklchToHex(L, 0, h)!;
  for (let i = 0; i < 24; i += 1) {
    const mid = (lo + hi) / 2;
    const hex = oklchToHex(L, mid, h);
    if (hex) { best = hex; lo = mid; } else { hi = mid; }
  }
  return { hex: best, C: lo };
}

/**
 * Chroma envelope across the ramp. Mid steps carry the most colour; the
 * lightest and darkest steps ease off, because a near-white or near-black
 * step at full chroma reads as a different hue rather than the same one
 * lighter or darker.
 */
function chromaFor(seedC: number, L: number): number {
  const peak = 0.62;                       // lightness where chroma peaks
  const falloff = 1 - Math.abs(L - peak) * 1.25;
  return Math.max(0.02, seedC * Math.max(0.25, falloff));
}

const lines: string[] = [];
const report: string[] = [];
for (const [role, seed] of Object.entries(SEEDS)) {
  const { C, h } = hexToOklch(seed);
  const row: string[] = [];
  for (const [step, L] of Object.entries(STEPS)) {
    const { hex } = fitChroma(L, chromaFor(C, L), h);
    lines.push(`  --mx-${role}-${step}: ${hex};`);
    row.push(`${step}:${hex}`);
  }
  report.push(`${role.padEnd(8)} seed ${seed}  hue ${h.toFixed(1).padStart(5)}  ${row.join(" ")}`);
}

console.log(`/* Generated by scripts/src/build-mx-ramps.ts — do not hand-edit.\n   Seeds: ${Object.entries(SEEDS).map(([k, v]) => `${k} ${v}`).join(" · ")}\n   One shared perceptual lightness scale: ${Object.entries(STEPS).map(([s, l]) => `${s}=${l}`).join(" ")} */`);
console.log(lines.join("\n"));
console.error("\n" + report.join("\n") + "\n");
