-- METRIX IAP — Migration 0009: Global variable registry (closes Blueprint v2.0 §11.2 / §16 gap)
-- Source: VARIABLES_REGISTRY (Google Doc, live canonical source, last modified within the hour
-- this migration was built), cross-verified against Master Concept Variable Table.xlsx and
-- Master Angle Variable Table.xlsx (identical content, confirms no drift between sources).
--
-- Config-as-data, same pattern as cohort_definitions (Migration 0002): a new variable code is a
-- new row, never a schema change. variable_code is global and immutable across all clients —
-- this is distinct from client-local library codes (which live in per-client tables, not here).
--
-- Deprecation handling: rows are never deleted. A deprecated code gets status = 'deprecated' and
-- superseded_by pointing at its replacement, so historical creative tagged with the old code
-- stays resolvable. Confirmed real case: PR_SocialProof -> PR_MassProof (effective 2025-11-08).

create table global_variable_registry (
  variable_code text primary key,
  variable_family text not null check (variable_family in ('CN','FW','TN','ST','AW','HP','PR','HK','CTA')),
  label text not null,
  definition text not null,
  strategic_role text,
  -- true only for the four required-in-every-stack families: CN, FW, TN, HK (VARIABLES_REGISTRY,
  -- "Required Variables" section). ST/AW/HP/PR/CTA are optional, situational additions.
  is_required_in_stack boolean not null default false,
  typical_pairings jsonb not null default '[]',
  -- populated for angle variables (FW/TN/ST/AW/HP/PR/HK/CTA): which CN_ codes this pairs with.
  best_for_concepts jsonb not null default '[]',
  -- CN_-only fields. Empty array for every non-CN row.
  common_elements jsonb not null default '[]',
  typical_formats jsonb not null default '[]',
  best_funnel_stage jsonb not null default '[]',
  -- angle-variable-only field. Empty array for CN_ rows.
  performance_indicators jsonb not null default '[]',
  status text not null default 'active' check (status in ('active', 'deprecated')),
  superseded_by text references global_variable_registry(variable_code),
  deprecation_note text,
  effective_date date not null default current_date,
  schema_version text not null default 'v1.0',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (variable_code like variable_family || '_%'),
  check (status = 'active' or superseded_by is not null)
);

create index idx_global_variable_registry_family on global_variable_registry(variable_family);
create index idx_global_variable_registry_status on global_variable_registry(status);
-- METRIX IAP -- Seed 0009: global_variable_registry
-- Source: VARIABLES_REGISTRY (live Google Doc), cross-verified against Master Concept
-- Variable Table.xlsx and Master Angle Variable Table.xlsx (identical content -- no drift).
-- 51 rows: 49 active + 2 deprecated (CN_PainFirst -> HK_Problem, PR_SocialProof -> PR_MassProof).
-- Includes TN_Relatable, confirmed active-in-use but missing from VARIABLES_REGISTRY/Master
-- Angle Variable Table; sourced from IAP_CORRELATION_INTELLIGENCE_v1.xlsx's own Variable
-- Codes tab and confirmed active in MST matrix validation.

insert into global_variable_registry
  (variable_code, variable_family, label, definition, strategic_role, is_required_in_stack,
   typical_pairings, best_for_concepts, common_elements, typical_formats, best_funnel_stage,
   performance_indicators, status, superseded_by, deprecation_note, schema_version)
values
  ('CN_Testimonial', 'CN', 'Testimonial', 'A story or quote from a customer highlighting results or satisfaction', 'Builds social proof and relatability', true, '[]', '[]', '["Quote overlay text", "Face-forward UGC footage", "Real People framing", "Before/after states", "Specific outcome metrics"]', '["Video", "Static with quote card"]', '["MOFU", "BOFU"]', '[]', 'active', null, null, 'v1.0'),
  ('CN_FounderStory', 'CN', 'Founder Story', 'A narrative about the brand''s origin, mission, or personal motivation', 'Drives authority and trust', true, '[]', '[]', '["Talking-head format", "Direct-to-camera delivery", "Meet the Founder CTA", "Origin narrative", "Mission-driven framing"]', '["Video", "Carousel with founder journey"]', '["TOFU", "MOFU"]', '[]', 'active', null, null, 'v1.0'),
  ('CN_ProductDemo', 'CN', 'Product Demo', 'Visual explanation of how the product functions and delivers benefit', 'Offers clarity and builds belief through proof', true, '[]', '[]', '["Sequential walkthrough", "Over-the-shoulder view", "See It Work CTA", "Product in use", "Feature callouts"]', '["Video", "Carousel", "GIF"]', '["MOFU", "BOFU"]', '[]', 'active', null, null, 'v1.0'),
  ('CN_ProductSpecs', 'CN', 'Product Specs', 'Feature breakdown with emphasis on what and why it matters', 'Appeals to rational decision-making', true, '[]', '[]', '["Side-by-side feature cards", "Bullet point overlays", "Why It''s Different CTA", "Comparison tables", "Technical details"]', '["Static", "Carousel"]', '["MOFU"]', '[]', 'active', null, null, 'v1.0'),
  ('CN_Comparison', 'CN', 'Comparison', 'Direct comparison to alternatives, old habits, or competitors', 'Supports objection handling and differentiation', true, '[]', '[]', '["Comparison tables", "Checklists", "Vs. visuals", "Upgrade Now CTA", "Before state emphasis"]', '["Static", "Carousel", "Video"]', '["MOFU", "BOFU"]', '[]', 'active', null, null, 'v1.0'),
  ('CN_ValueStack', 'CN', 'Value Stack', 'Presentation of all included benefits, bonuses, or cost savings', 'Maximizes conversion intent', true, '[]', '[]', '["Bundle graphic", "Pricing overlay", "Countdown timer", "Claim My Offer CTA", "Value breakdown"]', '["Static", "Video"]', '["BOFU"]', '[]', 'active', null, null, 'v1.0'),
  ('CN_Lifestyle', 'CN', 'Lifestyle Outcome', 'Focus on emotional or practical outcomes in the user''s day-to-day life', 'Drives desire and identity-based appeal', true, '[]', '[]', '["Aspirational imagery", "Lifestyle framing", "Identity-based messaging", "Wake Up Smarter style CTA", "Emotional outcome focus"]', '["Static", "Video", "Carousel"]', '["TOFU", "MOFU"]', '[]', 'active', null, null, 'v1.0'),
  ('CN_BehaviorShift', 'CN', 'Behavior Change', 'Demonstrates transformation in routine, mindset, or user habits', 'Effective for habit-focused categories', true, '[]', '[]', '["Before-after frames", "Repeatable systems", "Change How You Start CTA", "Habit formation language", "Transformation journey"]', '["Video", "Carousel"]', '["MOFU"]', '[]', 'active', null, null, 'v1.0'),
  ('CN_ConditionSupport', 'CN', 'Condition Support', 'Addresses specific health, emotional, or sensory challenges. Avatar-specific application, not a distinct structural format -- can be combined with any narrative structure (testimonial, demo, etc.) when targeting condition-specific audiences.', 'Tailors messaging to niche or high-empathy verticals', true, '[]', '[]', '["Calm tone", "Expert quotes", "Sensory-safe visuals", "Explore Relief CTA", "Empathetic framing"]', '["Video", "Static"]', '["TOFU", "MOFU"]', '[]', 'active', null, null, 'v1.0'),
  ('CN_EnvironmentHack', 'CN', 'Environment Improvement', 'Shows how product enhances relational, social, or shared environments. Avatar-specific application, not a distinct structural format -- can be combined with any narrative structure when emphasizing interpersonal benefits.', 'Emphasizes external tension relief and interpersonal benefit', true, '[]', '[]', '["Co-living visuals", "No more disruptions copy", "Sleep In Peace CTA", "Relationship harmony focus", "Shared benefit framing"]', '["Video", "Static"]', '["TOFU", "MOFU"]', '[]', 'active', null, null, 'v1.0'),
  ('FW_PAS', 'FW', 'PAS (Problem-Agitate-Solution)', 'Opens with problem, agitates pain, presents solution', 'Ideal for pain-led scroll-stopping and TOFU delivery', true, '["TN_Emotional", "HK_Problem", "ST_TOFU"]', '["CN_Comparison", "CN_BehaviorShift"]', '[]', '[]', '[]', '["High CTR", "Strong ATC rate", "Problem-aware audience response"]', 'active', null, null, 'v1.0'),
  ('FW_AIDA', 'FW', 'AIDA (Attention-Interest-Desire-Action)', 'Builds curiosity, creates interest, drives desire, prompts action', 'Good for longer BOFU journeys or value-based breakdowns', true, '["TN_Rational", "ST_BOFU", "PR_DataDriven"]', '["CN_ValueStack", "CN_ProductDemo", "CN_ProductSpecs"]', '[]', '[]', '[]', '["Strong CVR", "Low drop-off", "Complete funnel engagement"]', 'active', null, null, 'v1.0'),
  ('FW_FAB', 'FW', 'FAB (Feature-Advantage-Benefit)', 'What it does, why it matters, what you gain', 'MOFU format used for demonstrating technical utility', true, '["TN_Rational", "ST_MOFU", "PR_VisualDemo"]', '["CN_ProductDemo", "CN_ProductSpecs", "CN_Comparison"]', '[]', '[]', '[]', '["Solution-aware audience engagement", "High consideration metrics"]', 'active', null, null, 'v1.0'),
  ('FW_BAB', 'FW', 'BAB (Before-After-Bridge)', 'Current state, desired state, how to get there', 'Strong for transformational/lifestyle messaging', true, '["TN_Aspirational", "HK_Benefit", "ST_MOFU"]', '["CN_Lifestyle", "CN_BehaviorShift", "CN_Comparison"]', '[]', '[]', '[]', '["Identity-shift audience response", "Aspirational engagement"]', 'active', null, null, 'v1.0'),
  ('FW_StoryBrand', 'FW', 'StoryBrand', 'Hero''s journey with brand as the guide', 'Great for founder story, longform, or testimonial-narrative blends', true, '["TN_Emotional", "HK_Story", "PR_Testimonial"]', '["CN_FounderStory", "CN_Testimonial", "CN_BehaviorShift"]', '[]', '[]', '[]', '["High engagement time", "Emotional resonance", "Brand recall"]', 'active', null, null, 'v1.0'),
  ('TN_Emotional', 'TN', 'Emotional', 'Empathetic, heartfelt, identity-driven messaging', 'Drives connection and relatability', true, '["FW_PAS", "FW_StoryBrand", "HK_Story", "HK_Problem"]', '["CN_Testimonial", "CN_FounderStory", "CN_ConditionSupport"]', '[]', '[]', '[]', '["High engagement", "Social sharing", "Comments/reactions"]', 'active', null, null, 'v1.0'),
  ('TN_Rational', 'TN', 'Rational', 'Logical, data-led, benefit-focused messaging', 'Good for awareness-aware users, especially BOFU', true, '["FW_FAB", "FW_AIDA", "PR_DataDriven", "ST_BOFU"]', '["CN_ProductSpecs", "CN_ProductDemo", "CN_Comparison"]', '[]', '[]', '[]', '["High CVR", "Low CPA", "Solution-aware conversions"]', 'active', null, null, 'v1.0'),
  ('TN_Playful', 'TN', 'Playful', 'Irreverent, witty, humor-driven tone', 'Scroll-stopping and challenger brand use', true, '["HK_Shock", "HK_Curiosity", "ST_TOFU"]', '["CN_Comparison"]', '[]', '[]', '[]', '["Very high CTR", "Viral potential", "Young audience engagement"]', 'active', null, null, 'v1.0'),
  ('TN_Assertive', 'TN', 'Assertive', 'Confident, direct, credibility-led messaging', 'Expert tone for technical or authority-based messages', true, '["PR_Expert", "FW_FAB", "ST_MOFU"]', '["CN_FounderStory", "CN_ProductSpecs", "CN_ValueStack"]', '[]', '[]', '[]', '["Trust signals", "High consideration", "Professional audience"]', 'active', null, null, 'v1.0'),
  ('TN_Aspirational', 'TN', 'Aspirational', 'Ideal-self oriented, motivational messaging', 'Effective for lifestyle or identity shift angles', true, '["FW_BAB", "HK_Benefit", "CN_Lifestyle"]', '["CN_Lifestyle", "CN_BehaviorShift"]', '[]', '[]', '[]', '["Identity-based engagement", "Desire signals", "Lifestyle audience"]', 'active', null, null, 'v1.0'),
  ('TN_Relatable', 'TN', 'Relatable', 'Peer-to-peer voice. Conversational, UGC-style, informal.', 'Effective for peer-recommendation and UGC-style creative where authenticity outweighs polish', true, '["PR_Testimonial", "HK_Story", "FW_StoryBrand"]', '["CN_Testimonial", "CN_Lifestyle"]', '[]', '[]', '[]', '["MOFU engagement", "UGC-style resonance"]', 'active', null, null, 'v1.0'),
  ('ST_TOFU', 'ST', 'TOFU (Top of Funnel)', 'Attention, education, or pain introduction', 'Used for attention, education, or pain intro', false, '["AW_Unaware", "HK_Problem", "HK_Curiosity"]', '["CN_Lifestyle", "CN_ConditionSupport"]', '[]', '[]', '[]', '["CTR", "Engagement rate", "Reach"]', 'active', null, null, 'v1.0'),
  ('ST_MOFU', 'ST', 'MOFU (Middle of Funnel)', 'Solution comparison, utility, credibility-building', 'Solution comparison, utility, credibility-building', false, '["AW_SolutionAware", "FW_FAB", "PR_VisualDemo"]', '["CN_ProductDemo", "CN_Comparison", "CN_BehaviorShift"]', '[]', '[]', '[]', '["ATC rate", "Engagement time", "Video watch %"]', 'active', null, null, 'v1.0'),
  ('ST_BOFU', 'ST', 'BOFU (Bottom of Funnel)', 'Offer, urgency, value stack, retargeting-focused', 'Offer, urgency, value stack, retargeting-focused', false, '["AW_MostAware", "FW_AIDA", "HP_Money"]', '["CN_ValueStack", "CN_ProductSpecs", "CN_Testimonial"]', '[]', '[]', '[]', '["CVR", "ROAS", "Purchase rate"]', 'active', null, null, 'v1.0'),
  ('AW_Unaware', 'AW', 'Unaware', 'Prospect doesn''t know the problem exists', 'Needs educational or lifestyle-based hooks', false, '["ST_TOFU", "HK_Story", "TN_Emotional"]', '["CN_Lifestyle", "CN_EnvironmentHack"]', '[]', '[]', '[]', '["Discovery engagement", "Educational content consumption"]', 'active', null, null, 'v1.0'),
  ('AW_ProblemAware', 'AW', 'Problem-Aware', 'Prospect feels the pain but doesn''t know the fix', 'Ideal for agitation hooks or trust-building', false, '["FW_PAS", "HK_Problem", "ST_TOFU"]', '["CN_ConditionSupport"]', '[]', '[]', '[]', '["Pain resonance", "Problem identification engagement"]', 'active', null, null, 'v1.0'),
  ('AW_SolutionAware', 'AW', 'Solution-Aware', 'Prospect knows general solution type', 'Positioning and differentiator-led messaging', false, '["ST_MOFU", "FW_FAB", "CN_Comparison"]', '["CN_Comparison", "CN_ProductSpecs", "CN_ProductDemo"]', '[]', '[]', '[]', '["Comparison shopping signals", "Feature evaluation"]', 'active', null, null, 'v1.0'),
  ('AW_MostAware', 'AW', 'Most-Aware', 'Prospect knows the product/offer', 'Used for retargeting, urgency, BOFU stack', false, '["ST_BOFU", "FW_AIDA", "HP_Money"]', '["CN_ValueStack", "CN_Testimonial"]', '[]', '[]', '[]', '["Direct response", "Conversion rate", "ROAS"]', 'active', null, null, 'v1.0'),
  ('HP_Time', 'HP', 'Time', 'Messaging around speed, simplicity, or saving time', 'Common for productivity, family, or sleep tools', false, '["TN_Rational", "FW_FAB"]', '["CN_ProductDemo", "CN_BehaviorShift"]', '[]', '[]', '[]', '["Efficiency-seeking audience response"]', 'active', null, null, 'v1.0'),
  ('HP_Money', 'HP', 'Money', 'Highlights cost, ROI, or budget concerns', 'Useful in B2C or competitive comparison ads', false, '["ST_BOFU", "CN_ValueStack", "FW_AIDA"]', '["CN_ValueStack", "CN_Comparison"]', '[]', '[]', '[]', '["Price-conscious audience engagement"]', 'active', null, null, 'v1.0'),
  ('HP_Confidence', 'HP', 'Confidence', 'Emotional pain rooted in self-belief or performance', 'Effective in transformation categories', false, '["TN_Emotional", "FW_BAB"]', '["CN_Lifestyle", "CN_BehaviorShift"]', '[]', '[]', '[]', '["Identity-shift signals", "Transformation interest"]', 'active', null, null, 'v1.0'),
  ('HP_Overwhelm', 'HP', 'Overwhelm', 'Stress from mental load, multitasking, or chaos', 'Often used in parenting, wellness, or planning', false, '["TN_Emotional", "HK_Problem"]', '["CN_EnvironmentHack", "CN_ConditionSupport"]', '[]', '[]', '[]', '["Stress relief interest", "Simplification appeal"]', 'active', null, null, 'v1.0'),
  ('HP_Loneliness', 'HP', 'Loneliness', 'Messaging around isolation, disconnection, or unmet needs', 'High empathy / identity narrative campaigns', false, '["TN_Emotional", "FW_StoryBrand"]', '["CN_Testimonial", "CN_ConditionSupport"]', '[]', '[]', '[]', '["Connection-seeking engagement", "Community interest"]', 'active', null, null, 'v1.0'),
  ('PR_Testimonial', 'PR', 'Testimonial', 'Social proof from real user quote or face', 'Used in UGC, quote cards, or video overlays', false, '["CN_Testimonial", "TN_Emotional"]', '["CN_Testimonial"]', '[]', '[]', '[]', '["Trust signals", "Relatability metrics"]', 'active', null, null, 'v1.0'),
  ('PR_Expert', 'PR', 'Expert', 'Doctor, founder, or credentialed endorsement', 'Adds authority to rational claims', false, '["TN_Assertive", "FW_FAB"]', '["CN_FounderStory", "CN_ConditionSupport"]', '[]', '[]', '[]', '["Credibility engagement", "Professional audience"]', 'active', null, null, 'v1.0'),
  ('PR_DataDriven', 'PR', 'Data', 'Includes charts, stats, or quant-based validation', 'Often paired with rational tone or AIDA', false, '["TN_Rational", "FW_AIDA"]', '["CN_ProductSpecs", "CN_Comparison"]', '[]', '[]', '[]', '["Logic-driven conversions", "B2B/analytical audience"]', 'active', null, null, 'v1.0'),
  ('PR_MassProof', 'PR', 'Mass Proof', 'Volume and scale indicators (Over 100K Users, Thousands Switched, #1 Rated)', 'Demonstrates widespread adoption and social validation through numbers', false, '["ST_BOFU", "HK_SocialProof"]', '["CN_ValueStack", "CN_Testimonial"]', '[]', '[]', '[]', '["Bandwagon effect", "Validation seeking"]', 'active', null, null, 'v1.0'),
  ('PR_VisualDemo', 'PR', 'Visual Demo', 'Showing the product solving the problem visually', 'Can apply to any concept; high-performance MOFU/BOFU format', false, '["CN_ProductDemo", "FW_FAB"]', '["CN_ProductDemo", "CN_Comparison"]', '[]', '[]', '[]', '["Understanding signals", "See-it-work engagement"]', 'active', null, null, 'v1.0'),
  ('HK_Problem', 'HK', 'Problem Hook', 'Opens with visceral issue or key symptom. Use for all pain-first creative approaches.', 'Strong for pain-first ads, especially TOFU. Replaces the former CN_PainFirst concept -- any pain-led creative uses HK_Problem plus the appropriate structural concept code.', true, '["FW_PAS", "TN_Emotional", "ST_TOFU"]', '["CN_Comparison"]', '[]', '[]', '[]', '["High CTR", "Pain-aware audience stops"]', 'active', null, null, 'v1.0'),
  ('HK_Benefit', 'HK', 'Benefit Hook', 'Opens with outcome or desired state', 'Effective for aware or aspirational users', true, '["FW_BAB", "TN_Aspirational", "ST_MOFU"]', '["CN_Lifestyle", "CN_BehaviorShift"]', '[]', '[]', '[]', '["Desire signals", "Aspirational engagement"]', 'active', null, null, 'v1.0'),
  ('HK_Curiosity', 'HK', 'Curiosity Hook', 'Opens with a question or open loop', 'Scroll-stopper; good for UGC and carousels', true, '["TN_Playful", "ST_TOFU"]', '["CN_ProductDemo", "CN_Comparison"]', '[]', '[]', '[]', '["Very high CTR", "Info-seeking clicks"]', 'active', null, null, 'v1.0'),
  ('HK_Shock', 'HK', 'Shock Hook', 'Uses jarring visuals or unexpected phrasing', 'Ideal for UGC, humor, or interruption strategy', true, '["TN_Playful", "ST_TOFU"]', '[]', '[]', '[]', '[]', '["Viral potential", "Pattern interrupt success"]', 'active', null, null, 'v1.0'),
  ('HK_Story', 'HK', 'Story Hook', 'Opens with personal anecdote or scenario', 'Used in founder, testimonial, and narrative-heavy creatives', true, '["FW_StoryBrand", "TN_Emotional"]', '["CN_FounderStory", "CN_Testimonial"]', '[]', '[]', '[]', '["Engagement time", "Emotional resonance"]', 'active', null, null, 'v1.0'),
  ('HK_SocialProof', 'HK', 'Social Proof Hook', 'Leads with authority or scale (# of customers, expert quote)', 'Good for retargeting or claim validation', true, '["PR_MassProof", "ST_BOFU"]', '["CN_Testimonial", "CN_ValueStack"]', '[]', '[]', '[]', '["Trust building", "Validation seeking"]', 'active', null, null, 'v1.0'),
  ('CTA_Action', 'CTA', 'Action CTA', 'Direct action-oriented language (Shop Now, Buy Today, Get Started, Add to Cart)', 'Drives immediate conversion, best for BOFU and high-intent audiences', false, '[]', '[]', '[]', '[]', '[]', '[]', 'active', null, null, 'v1.0'),
  ('CTA_Low', 'CTA', 'Low-Commitment CTA', 'Soft exploration language (Learn More, Explore, Discover, See How)', 'Reduces friction for TOFU, good for awareness-building', false, '[]', '[]', '[]', '[]', '[]', '[]', 'active', null, null, 'v1.0'),
  ('CTA_Urgency', 'CTA', 'Urgency CTA', 'Time-sensitive language (Limited Time, Act Now, Today Only, Ending Soon)', 'Creates scarcity, effective for promotions and retargeting', false, '[]', '[]', '[]', '[]', '[]', '[]', 'active', null, null, 'v1.0'),
  ('CTA_Social', 'CTA', 'Social Proof CTA', 'Bandwagon effect language (Join Thousands, See Why, Everyone''s Switching, Be Part Of)', 'Leverages social validation, strong for community-driven products', false, '[]', '[]', '[]', '[]', '[]', '[]', 'active', null, null, 'v1.0'),
  ('CTA_Free', 'CTA', 'Free/Trial CTA', 'Risk-reduction language (Start Free, Try Free, No Credit Card, Risk-Free Trial)', 'Lowers barrier to entry, excellent for SaaS and subscription models', false, '[]', '[]', '[]', '[]', '[]', '[]', 'active', null, null, 'v1.0'),
  ('CN_PainFirst', 'CN', 'Pain First (deprecated)', 'Deprecated concept code for pain-led creative opens.', 'Superseded -- pain-led creative is now expressed as HK_Problem plus the appropriate structural concept code (e.g. CN_Testimonial + HK_Problem), not as its own concept.', false, '[]', '[]', '[]', '[]', '[]', '[]', 'deprecated', 'HK_Problem', 'Deprecated: pain-first is a hook strategy (HK_Problem), not a standalone structural concept.', 'v1.0'),
  ('PR_SocialProof', 'PR', 'Social Proof (deprecated)', 'Deprecated proof-type code, superseded to clarify the distinction from PR_Testimonial (both are forms of social proof).', 'Deprecated -- use PR_MassProof.', false, '[]', '[]', '[]', '[]', '[]', '[]', 'deprecated', 'PR_MassProof', 'Renamed effective 2025-11-08 per VARIABLES_REGISTRY. Historical data tagged PR_SocialProof should be migrated to PR_MassProof.', 'v1.0');