// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/workflow-approaches/ActionInbox.tsx": () => import("../components/mockups/workflow-approaches/ActionInbox.tsx"),
  "./components/mockups/analysis-overview/SignalFeed.tsx": () => import("../components/mockups/analysis-overview/SignalFeed.tsx")
};
