// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/analysis-overview/AnalystBriefing.tsx": () => import("../components/mockups/analysis-overview/AnalystBriefing.tsx"),
  "./components/mockups/analysis-overview/CommandDeck.tsx": () => import("../components/mockups/analysis-overview/CommandDeck.tsx"),
  "./components/mockups/analysis-overview/FunnelMap.tsx": () => import("../components/mockups/analysis-overview/FunnelMap.tsx")
};
